eureka:
  client:
    service-url:
      defaultZone: http://10.148.0.50:9001/eureka, http://10.148.0.49:9001/eureka, http://10.148.0.48:9001/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    lk.ijse.eca: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG


jwt:
  secret: random-secret-key-for-jwt-signing
  expiration: 3600000 # 1 hour in milliseconds